# Generated by Django 5.2.10 on 2026-02-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('accessories', 'Accessories')], default='men', max_length=20),
        ),
    ]
